venv support for both

diff --git a/Task2/Makefile b/Task2/Makefile
--- a/Task2/Makefile
+++ b/Task2/Makefile
@@ -1,20 +1,36 @@
-py = $(shell if [ -d $(PWD)/'.venv' ]; then echo $(PWD)/".venv/bin/python3"; else echo "python3"; fi)
-pip = $(py) -m pip
+ifeq ($(OS),Windows_NT)
+	OOS := Windows
+else
+	OOS := other
+endif
 
 all: build
 
-build:
+build: venv
 	@echo "Building configuration docker-compose up in detached mode...\n"
 	@docker-compose up -d
-	@echo "Installling python packages using pip install...\n"
-	${pip} install pymongo requests fastapi uvicorn python-dotenv pandas wheel
 	@echo "executing dataReceiveStoreEnv.py\n"
-	${py} dataReceiveStoreEnv.py
+ifeq ($(OOS),Windows)
+	@echo "executing dataReceiveStoreEnv.py\n"
+	@if [ -f venv/Scripts/activate ]; then venv/Scripts/python dataReceiveStoreEnv.py; else python dataReceiveStoreEnv.py; fi
 	@echo "executing mainEnv.py\n"
-	${py} mainEnv.py
+	@if [ -f venv/Scripts/activate ]; then venv/Scripts/python mainEnv.py; else python mainEnv.py; fi
+else
+	@echo "executing dataReceiveStoreEnv.py\n"
+	@if [ -f venv/bin/activate ]; then venv/bin/python3 dataReceiveStoreEnv.py; else python3 dataReceiveStoreEnv.py; fi
+	@echo "executing mainEnv.py\n"
+	@if [ -f venv/bin/activate ]; then venv/bin/python3 mainEnv.py; else python3 mainEnv.py; fi
+endif
 
-install:
-	${pip} install pymongo requests fastapi uvicorn python-dotenv pandas wheel
+venv:
+ifeq ($(OOS),Windows)
+	-python -m venv venv; VENV_EXIT_CODE=$$?; \
+	if [ $$VENV_EXIT_CODE -eq 0 ]; then . venv/Scripts/activate; venv/Scripts/pip install pymongo requests fastapi uvicorn python-dotenv pandas wheel termcolor;  else echo "Failed to create virtual environment"; rm -r venv/; exit 1; fi
+else
+	-python3 -m venv venv; VENV_EXIT_CODE=$$?; \
+	if [ $$VENV_EXIT_CODE -eq 0 ]; then . venv/bin/activate; venv/bin/pip install pymongo requests fastapi uvicorn python-dotenv pandas wheel termcolor; else echo "Failed to create virtual environment"; rm -r venv/; exit 1; fi
+endif
+	@echo "Virtual environment detection passed successfully."
 
 up:
 	@docker-compose up -d
@@ -23,34 +39,40 @@ down:
 	@docker-compose down
 
 stop-remove-containers:
+	@echo "Stopping and removing containers\n"
 	@CONTAINERS=$$(docker ps -qa); \
 	if [ -n "$$CONTAINERS" ]; then \
-		docker stop $$CONTAINERS; \
-		docker rm $$CONTAINERS; \
+	docker stop $$CONTAINERS; \
+	docker rm $$CONTAINERS; \
 	else \
-		echo "No running containers to stop/rm."; \
+	echo "No running containers to stop/rm."; \
 	fi
 
 remove-volume:
+	@echo "Cleaning all volumes"
 	@DOCKERVOLUME=$$(docker volume ls -q); \
 	if [ -n "$$DOCKERVOLUME" ]; then \
-		docker volume rm  $$DOCKERVOLUME; \
+	docker volume rm  $$DOCKERVOLUME; \
 	else \
-		echo "No volumes to rm."; \
+	echo "No volumes to rm."; \
 	fi
 
-fclean: stop-remove-containers  remove-volume
-	@echo "Total clean of all configurations docker\n"
-	@docker system prune -a
+remove_image:
+	@echo "Removing all images"
 	@for image in $$(docker images -qa); do \
-		if docker image inspect -f '{{.Id}} {{.Parent}}' $$image | grep -q -E '^$(image)'; then \
-			docker rmi -f $$image; \
-		else \
-			echo "no images to remove"; \
-		fi; \
+	if docker image inspect -f '{{.Id}} {{.Parent}}' $$image | grep -q -E '^$(image)'; then \
+	docker rmi -f $$image; \
+	else \
+	echo "no images to remove"; \
+	fi; \
 	done
 
-.PHONY	: all build down re clean fclean
+fclean: stop-remove-containers  remove-volume remove_image
+	@docker system prune -a
+	@echo "All docker configuration cleaned!\n"
+
+
+.PHONY	: all build down re clean fclean venv install up stop-remove-containers remove-volume
 
 re: fclean
-	all
+	$(MAKE) all
